name: Examples Deployment
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_EXAMPLES_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_EXAMPLES_PROJECT_ID }}
on:
  push:
    branches:
      - main
    paths:
      - 'examples/**'
      - 'library/visualization/**'
      - '.github/workflows/examples-deploy.yml'
  release:
    types: [published]
jobs:
  Deploy-Production:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
      
      - name: Install root dependencies (for library)
        run: npm ci
      
      - name: Install examples dependencies
        working-directory: ./examples
        run: npm ci
      
      - name: Pull Vercel Environment Information
        working-directory: ./examples
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
      
      - name: Build Project Artifacts
        working-directory: ./examples
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}
      
      - name: Deploy Project Artifacts to Vercel
        working-directory: ./examples
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
